### PR TITLE
truncate table columns via css

### LINKED ISSUE #506: Truncate media items, sources, jobs via css
It is preferred to truncate text via css and not via server side functions because the browser will show more on larger screens and on smaller screens will show a tooltip with the complete text on mouseover.

Bildschirmfoto 2024-12-11 um 21 46 39

Using tailwind use class="truncate max-w-xs" on columns to be truncated.

### PR DESCRIPTION
**Pull request by robertkleinschuster**
## What's new?

N/A

## What's changed?

- Truncating titles in tables via css to allow browser to show more of the title if space is available.
  - closes #506
  - related to #458

## What's fixed?

N/A

## Any other comments?

N/A

- [x] I am the original author of this code and I am giving it freely to the community and Pinchflat project maintainers

### CODE REVIEW

**Comment by kieraneglin** [comment]
Thank you for these PRs! I'll review and test them out tomorrow 🤙

**Comment by kieraneglin** [comment]
This is great! I'm happy with this as-is, but I was wondering if you'd be game to remove the other uses of the truncate method. It's mostly small things like `Results for "{StringUtils.truncate(@search_term, 50)}"` on the search page or `Editing "{StringUtils.truncate(@media_item.title, 35)}"` on the media item edit page.  I think it'd be ideal if we could get to the point where the `StringUtils.truncate` method was removed entirely

**Comment by robertkleinschuster** [comment]
> This is great! I'm happy with this as-is, but I was wondering if you'd be game to remove the other uses of the truncate method. It's mostly small things like `Results for "{StringUtils.truncate(@search_term, 50)}"` on the search page or `Editing "{StringUtils.truncate(@media_item.title, 35)}"` on the media item edit page. I think it'd be ideal if we could get to the point where the `StringUtils.truncate` method was removed entirely

Yes, was planning on doing this already. I am a believer in small incremental change, small PRs. I knew the tables were straightforward but the other places i have to look into closley to not disrupt the layout.

**Comment by kieraneglin** [comment]
Fair enough! I'll merge this as-is and we'll go from there 🤙 

Thanks again!

**Pull request merged**
