### PR TITLE
OPML "secret" Route

### PR DESCRIPTION
**Pull request by robertkleinschuster**
## What's new?

N/A

## What's changed?

Add the possibility to set a env variable to define the secret OPML feed route. 
Only show "Copy OPML Feed" when the secret is set.
Only allow access to opml route when secret ist set and passed correctly.

#532 

## What's fixed?

N/A

## Any other comments?

N/A

- [x] I am the original author of this code and I am giving it freely to the community and Pinchflat project maintainers

### CODE REVIEW

**Comment by kieraneglin** [comment]
Good catch! Unfortunately, hiding this behind basic auth makes it much harder to use with podcast apps so I'm currently looking into a way to handle this through some other mechanism.

I'll let you know what I come up with!

**Comment by robertkleinschuster** [comment]
> Good catch! Unfortunately, hiding this behind basic auth makes it much harder to use with podcast apps so I'm currently looking into a way to handle this through some other mechanism.
> 
> I'll let you know what I come up with!

I changed it to the env var variant. But im curious what other ideas you have.

**Comment by kieraneglin** [comment]
Ah - thank you for the update! My approach is more similar to this update, but there are still some key differences. I'll tag you once that PR is up!

Thanks again for the good work 💪

**Comment by kieraneglin** [comment]
Closing in favour of #535 - let me know if you have any thoughts on that PR!

**Pull request closed without merging**
