### PR TITLE
[Docs] document that BASE_ROUTE_PATH requires the prefix to be stripped

### PR DESCRIPTION
**Pull request by jbergler**
## What's new?

N/A

## What's changed?

Tiny change to the readme to make the reverse proxy config easier to figure out. I had to dig into past PRs and found it in the discussion of #275 to figure it out.

## What's fixed?

N/A

## Any other comments?

N/A

- [X] I am the original author of this code and I am giving it freely to the community and Pinchflat project maintainers

### CODE REVIEW

**Comment by kieraneglin** [comment]
Hey there! Thanks for the PR (:

I like the idea, but I might just fix it at the source and strip prefixes when I'm parsing the base route so people don't have to think about it.

I'm going to be out of cell service for the next week so I'll come back to this on Monday!

**Comment by jbergler** [comment]
That'd be a great fix!

**Comment by kieraneglin** [comment]
@jbergler I'm just looking into this and I think I'm missing something. I don't use this kind of reverse proxy so that's very possible!

Essentially, I'm wondering what you mean by "prefix". Could you give me an example of a value for `BASE_ROUTE_PATH` that didn't work and one that ultimately did work?

**Comment by jbergler** [comment]
In my experience the idea of "reverse proxy" stopped defaulting to rewriting urls a good while back. The big proxies of the pre-'cloud native' era (ie things like nginx) would not do any rewriting of requests unless it was explicitly configured.

"Stripping the prefix" is how I've always heard the rewrite described if you wanted to host an app at example.com/my-app but wanted a `GET /my-app/` to arrive as `GET /` after the reverse proxy. In this case `/my-app` is the prefix.

I know that some of the cloud native proxies do this rewriting by default, but it's also not the common case, so I think you can solve this in one of a few ways
1. Just document the expectation of your app to not see the "base path" in the proxied requests
2. Expose a separate setting to configure the backends routes with / without the base path
3. Have the backend handle both. 

Option 3 might have weird behavior if you have something show up twice, eg a base path of `/foo` if you also have a route `foo/main` or something.

**Comment by kieraneglin** [comment]
Thanks for the followup! I'll admit that I haven't set up a path-based proxy in a long time and I must've forgot some of the nuance.

I've looked into what it would take to get the app working _without_ stripping prefixes and, bluntly, it would be a pain in the ass. Given that, I think option number 1 (and what you've presented in this PR) are the best options to get this going forward!

**Comment by kieraneglin** [comment]
Merged! Thank you 🤙

**Pull request merged**
